name: Doxygen

on:
   pull_request:

concurrency:
  group: doxygen-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  Doxygen:
    name: Run doxygen
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 100
    - name: Run check
      run: ./ci/copy_doxygen_files.sh
